from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    model_validator,
)

from app.models.assessment_question import (
    AssessmentQuestionAssetType,
    AssessmentQuestionType,
)
from app.models.assessment_question_extraction import (
    AssessmentQuestionExtractionStatus,
)


class AssessmentQuestionExtractionReviewStatus(StrEnum):
    """
    Teacher-review state for an extraction proposal.

    This is deliberately proposal-level state rather than an extraction-row
    status. The extraction itself remains COMPLETED until it is explicitly
    imported or otherwise superseded.
    """

    UNREVIEWED = "unreviewed"
    IN_PROGRESS = "in_progress"
    REVIEWED = "reviewed"


class AssessmentQuestionExtractionSource(BaseModel):
    """
    Source evidence identifying where a proposed question was detected.

    Source evidence is generated by the extractor and is never rewritten by a
    teacher review request.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    page_number: int = Field(
        ge=1,
    )

    line_number: int | None = Field(
        default=None,
        ge=1,
    )

    source_line: str | None = None


class AssessmentQuestionExtractionOption(BaseModel):
    """
    One structured answer option proposed for a question.

    ``is_correct`` is teacher/authoring metadata. Candidate-facing assessment
    endpoints must never expose it.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    text: str = Field(
        min_length=1,
        max_length=20_000,
    )

    order: int = Field(
        default=1,
        ge=1,
    )

    is_correct: bool = False

    feedback: str | None = Field(
        default=None,
        max_length=20_000,
    )


class AssessmentQuestionExtractionAsset(BaseModel):
    """
    One visual/resource proposed for a question.

    Extraction-owned provenance remains server-controlled. A detected asset may
    point at a generated crop through ``storage_path``. That path remains
    server-side storage metadata and is never accepted from a review request.

    ``content_url`` is derived by the API response layer and provides an
    authorised browser-facing route for displaying the asset. It is never
    persisted into proposal_data.

    ``source_bbox`` uses PDF/page coordinates and is kept with the proposal so
    the original location can be audited and, when needed, re-cropped.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    asset_type: AssessmentQuestionAssetType = AssessmentQuestionAssetType.FIGURE

    storage_path: str | None = None

    content_url: str | None = None

    original_filename: str | None = Field(
        default=None,
        max_length=255,
    )

    mime_type: str | None = Field(
        default=None,
        max_length=255,
    )

    file_size_bytes: int | None = Field(
        default=None,
        ge=0,
    )

    alt_text: str | None = Field(
        default=None,
        max_length=20_000,
    )

    caption: str | None = Field(
        default=None,
        max_length=20_000,
    )

    order: int = Field(
        default=1,
        ge=1,
    )

    candidate_visible: bool = True

    source_document_id: int | None = Field(
        default=None,
        gt=0,
    )

    source_page_number: int | None = Field(
        default=None,
        gt=0,
    )

    source_bbox: dict[str, Any] | None = None

    included: bool = True

    reviewed: bool = False


class AssessmentQuestionExtractionCandidate(BaseModel):
    """
    One machine-detected question candidate awaiting teacher review.

    The candidate is deliberately separate from the canonical
    AssessmentQuestion model. Extraction alone never creates live questions.

    Teacher edits are persisted back into the proposal copy only. Raw page
    evidence remains unchanged.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    question_number: str = Field(
        min_length=1,
    )

    text: str = ""

    marks: int | None = Field(
        default=None,
        ge=0,
    )

    depth: int = Field(
        default=0,
        ge=0,
    )

    parent_question_number: str | None = None

    question_type: AssessmentQuestionType = AssessmentQuestionType.WRITTEN

    options: list[AssessmentQuestionExtractionOption] = Field(
        default_factory=list,
    )

    assets: list[AssessmentQuestionExtractionAsset] = Field(
        default_factory=list,
    )

    included: bool = True

    source: AssessmentQuestionExtractionSource

    confidence: str = "candidate"

    requires_review: bool = True

    reviewed: bool = False


class AssessmentQuestionExtractionWarning(BaseModel):
    """
    Warning generated while reading or interpreting the source PDF.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    code: str = Field(
        min_length=1,
    )

    message: str = Field(
        min_length=1,
    )

    page_numbers: list[int] = Field(
        default_factory=list,
    )


class AssessmentQuestionExtractionDeclaredTotal(BaseModel):
    """
    A total-mark declaration found in the source question paper.

    Example:
        (Total 8 marks)
    """

    model_config = ConfigDict(
        extra="allow",
    )

    marks: int = Field(
        ge=0,
    )

    page_number: int = Field(
        ge=1,
    )

    line_number: int | None = Field(
        default=None,
        ge=1,
    )

    source_line: str | None = None


class AssessmentQuestionExtractionProposalSummary(BaseModel):
    """
    Summary statistics generated from an extraction proposal.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    detected_question_count: int = Field(
        default=0,
        ge=0,
    )

    questions_with_detected_marks: int = Field(
        default=0,
        ge=0,
    )

    detected_mark_sum: int = Field(
        default=0,
        ge=0,
    )

    included_question_count: int | None = Field(
        default=None,
        ge=0,
    )

    included_mark_sum: int | None = Field(
        default=None,
        ge=0,
    )


class AssessmentQuestionExtractionProposal(BaseModel):
    """
    Reviewable machine-generated interpretation of a question paper.

    ``auto_import_allowed`` remains false for the current architecture.
    A teacher must explicitly review and import the proposal before canonical
    assessment questions are created.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    parser_version: str = Field(
        min_length=1,
    )

    review_required: bool = True

    auto_import_allowed: bool = False

    review_status: AssessmentQuestionExtractionReviewStatus = (
        AssessmentQuestionExtractionReviewStatus.UNREVIEWED
    )

    reviewed_by_id: int | None = None

    reviewed_at: datetime | None = None

    review_notes: str | None = None

    questions: list[AssessmentQuestionExtractionCandidate] = Field(
        default_factory=list,
    )

    summary: AssessmentQuestionExtractionProposalSummary

    warnings: list[AssessmentQuestionExtractionWarning] = Field(
        default_factory=list,
    )

    declared_totals: list[AssessmentQuestionExtractionDeclaredTotal] = Field(
        default_factory=list,
    )


class AssessmentQuestionExtractionPageCandidate(BaseModel):
    """
    Candidate question detected directly from one source page.

    These records represent raw extraction evidence and are not teacher
    editable.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    question_number: str = Field(
        min_length=1,
    )

    text: str = ""

    marks: int | None = Field(
        default=None,
        ge=0,
    )

    page_number: int = Field(
        ge=1,
    )

    line_number: int = Field(
        ge=1,
    )

    source_line: str


class AssessmentQuestionExtractionPage(BaseModel):
    """
    Extracted evidence retained for one PDF page.
    """

    model_config = ConfigDict(
        extra="allow",
    )

    page_number: int = Field(
        ge=1,
    )

    has_extractable_text: bool

    text_length: int = Field(
        ge=0,
    )

    text: str = ""

    question_candidates: list[AssessmentQuestionExtractionPageCandidate] = Field(
        default_factory=list,
    )

    extraction_error: str | None = None


class AssessmentQuestionExtractionReviewAssetUpdate(BaseModel):
    """
    Teacher-editable state for one extractor-owned visual candidate.

    ``asset_index`` identifies an existing asset in the stored proposal.
    Storage paths, source document ids, page numbers and bounding boxes are
    deliberately absent so a browser request cannot forge extraction evidence.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    asset_index: int = Field(
        ge=0,
    )

    asset_type: AssessmentQuestionAssetType

    alt_text: str | None = Field(
        default=None,
        max_length=20_000,
    )

    caption: str | None = Field(
        default=None,
        max_length=20_000,
    )

    order: int = Field(
        ge=1,
    )

    candidate_visible: bool = True

    included: bool = True

    reviewed: bool = False


class AssessmentQuestionExtractionReviewQuestionUpdate(BaseModel):
    """
    Editable teacher-review fields for one proposal question.

    ``candidate_index`` identifies the existing proposal item. Source evidence,
    confidence metadata, and extractor evidence are intentionally absent from
    this request model so the client cannot replace them.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    candidate_index: int = Field(
        ge=0,
    )

    question_number: str = Field(
        min_length=1,
        max_length=100,
    )

    text: str = Field(
        default="",
        max_length=20_000,
    )

    marks: int | None = Field(
        default=None,
        ge=0,
        le=10_000,
    )

    parent_question_number: str | None = Field(
        default=None,
        max_length=100,
    )

    question_type: AssessmentQuestionType | None = None

    options: list[AssessmentQuestionExtractionOption] | None = None

    assets: list[AssessmentQuestionExtractionReviewAssetUpdate] | None = None

    included: bool = True

    @model_validator(
        mode="after",
    )
    def validate_collection_identity(
        self,
    ) -> AssessmentQuestionExtractionReviewQuestionUpdate:
        """
        Validate collection-local identities while permitting in-progress MCQ
        authoring.

        Full interaction rules are enforced only when the whole proposal is
        marked REVIEWED, so autosave can persist an option list while the
        teacher is still constructing it.
        """

        if self.options is not None:
            option_orders = [option.order for option in self.options]

            if len(option_orders) != len(set(option_orders)):
                raise ValueError(
                    "Question option order values must be unique.",
                )

        if self.assets is not None:
            asset_indexes = [asset.asset_index for asset in self.assets]

            if len(asset_indexes) != len(set(asset_indexes)):
                raise ValueError(
                    "Each asset_index may appear only once.",
                )

            asset_orders = [asset.order for asset in self.assets if asset.included]

            if len(asset_orders) != len(set(asset_orders)):
                raise ValueError(
                    "Included question asset order values must be unique.",
                )

        return self

    reviewed: bool = True


class AssessmentQuestionExtractionReviewUpdate(BaseModel):
    """
    Request used to save teacher edits to an extraction proposal.

    The request replaces the editable state of the proposal questions while
    preserving all machine-generated source evidence on the server.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    review_status: AssessmentQuestionExtractionReviewStatus = (
        AssessmentQuestionExtractionReviewStatus.IN_PROGRESS
    )

    review_notes: str | None = Field(
        default=None,
        max_length=10_000,
    )

    questions: list[AssessmentQuestionExtractionReviewQuestionUpdate] = Field(
        min_length=1,
    )

    @model_validator(
        mode="after",
    )
    def validate_candidate_indexes(
        self,
    ) -> AssessmentQuestionExtractionReviewUpdate:
        """
        Each original proposal candidate may appear at most once.
        """

        candidate_indexes = [question.candidate_index for question in self.questions]

        if len(candidate_indexes) != len(set(candidate_indexes)):
            raise ValueError("Each candidate_index may appear only once.")

        if self.review_status != AssessmentQuestionExtractionReviewStatus.REVIEWED:
            return self

        for question in self.questions:
            if not question.included:
                continue

            question_type = question.question_type or AssessmentQuestionType.WRITTEN

            options = question.options or []
            option_count = len(options)
            correct_count = sum(1 for option in options if option.is_correct)

            if (
                question_type
                in {
                    AssessmentQuestionType.WRITTEN,
                    AssessmentQuestionType.NUMERIC,
                    AssessmentQuestionType.DIAGRAM_ANNOTATION,
                    AssessmentQuestionType.STRUCTURAL,
                }
                and option_count > 0
            ):
                raise ValueError(
                    f"Question {question.question_number!r}: written, numeric, "
                    "diagram-annotation and structural questions cannot have "
                    "multiple-choice options.",
                )

            if question_type == AssessmentQuestionType.MULTIPLE_CHOICE_SINGLE:
                if option_count < 2:
                    raise ValueError(
                        f"Question {question.question_number!r}: a single-answer "
                        "multiple-choice question must have at least two options.",
                    )

                if correct_count != 1:
                    raise ValueError(
                        f"Question {question.question_number!r}: a single-answer "
                        "multiple-choice question must have exactly one correct "
                        "option.",
                    )

            if question_type == AssessmentQuestionType.MULTIPLE_CHOICE_MULTIPLE:
                if option_count < 2:
                    raise ValueError(
                        f"Question {question.question_number!r}: a multiple-answer "
                        "multiple-choice question must have at least two options.",
                    )

                if correct_count < 1:
                    raise ValueError(
                        f"Question {question.question_number!r}: a multiple-answer "
                        "multiple-choice question must have at least one correct "
                        "option.",
                    )

            if question_type == AssessmentQuestionType.TRUE_FALSE:
                if option_count != 2:
                    raise ValueError(
                        f"Question {question.question_number!r}: a true/false "
                        "question must have exactly two options.",
                    )

                if correct_count != 1:
                    raise ValueError(
                        f"Question {question.question_number!r}: a true/false "
                        "question must have exactly one correct option.",
                    )

            if question.assets is not None:
                unreviewed_assets = [
                    asset.asset_index
                    for asset in question.assets
                    if asset.included and not asset.reviewed
                ]

                if unreviewed_assets:
                    raise ValueError(
                        f"Question {question.question_number!r}: all included "
                        "visual assets must be reviewed before the proposal can "
                        "be marked reviewed.",
                    )

        return self


class AssessmentQuestionExtractionBaseResponse(BaseModel):
    """
    Shared extraction metadata returned through the API.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int

    assessment_id: int

    assessment_document_id: int

    requested_by_id: int

    imported_by_id: int | None = None

    version: int = Field(
        ge=1,
    )

    status: AssessmentQuestionExtractionStatus

    extractor_name: str

    extractor_version: str | None = None

    parser_version: str

    page_count: int | None = Field(
        default=None,
        ge=0,
    )

    text_page_count: int | None = Field(
        default=None,
        ge=0,
    )

    detected_question_count: int | None = Field(
        default=None,
        ge=0,
    )

    detected_markable_question_count: int | None = Field(
        default=None,
        ge=0,
    )

    detected_total_marks: int | None = Field(
        default=None,
        ge=0,
    )

    error_message: str | None = None

    started_at: datetime | None = None

    completed_at: datetime | None = None

    imported_at: datetime | None = None

    created_at: datetime

    updated_at: datetime


class AssessmentQuestionExtractionSummaryResponse(
    AssessmentQuestionExtractionBaseResponse,
):
    """
    Lightweight extraction response for history/status listings.

    Large page text and proposal JSON are intentionally omitted.
    """

    pass


class AssessmentQuestionExtractionResponse(
    AssessmentQuestionExtractionBaseResponse,
):
    """
    Full extraction response used by the review workspace.
    """

    source_metadata: dict[str, Any] | None = None

    page_data: list[AssessmentQuestionExtractionPage] | None = None

    proposal_data: AssessmentQuestionExtractionProposal | None = None


class AssessmentQuestionExtractionCreatedResponse(
    AssessmentQuestionExtractionResponse,
):
    """
    Response returned when a new extraction attempt is created.
    """

    message: str = "Question-paper extraction completed."


class AssessmentQuestionExtractionReviewResponse(
    AssessmentQuestionExtractionResponse,
):
    """
    Response returned after teacher review changes are saved.
    """

    message: str = "Question extraction review saved."


class AssessmentQuestionExtractionImportedQuestionResponse(BaseModel):
    """
    One canonical AssessmentQuestion created by explicit proposal import.

    ``synthesised`` is true for structural parent questions that did not exist
    as editable extraction candidates but were required to preserve hierarchy.
    """

    id: int

    question_number: str

    parent_question_id: int | None = None

    parent_question_number: str | None = None

    maximum_mark: Decimal = Field(
        ge=0,
    )

    order: int = Field(
        ge=1,
    )

    is_markable: bool

    question_type: AssessmentQuestionType = AssessmentQuestionType.WRITTEN

    option_count: int = Field(
        default=0,
        ge=0,
    )

    asset_count: int = Field(
        default=0,
        ge=0,
    )

    synthesised: bool = False

    source_candidate_index: int | None = Field(
        default=None,
        ge=0,
    )


class AssessmentQuestionExtractionImportResponse(
    AssessmentQuestionExtractionResponse,
):
    """
    Response returned after explicit reviewed-proposal import.

    Import is a distinct action from extraction and review. The response
    therefore reports both the final extraction state and the canonical
    questions created by the atomic import transaction.
    """

    message: str = "Reviewed question extraction imported."

    imported_question_count: int = Field(
        ge=0,
    )

    imported_markable_question_count: int = Field(
        ge=0,
    )

    synthesised_parent_count: int = Field(
        ge=0,
    )

    imported_total_marks: Decimal = Field(
        ge=0,
    )

    imported_questions: list[AssessmentQuestionExtractionImportedQuestionResponse] = (
        Field(
            default_factory=list,
        )
    )


class AssessmentQuestionExtractionHistoryResponse(BaseModel):
    """
    Extraction history for one source question-paper document.
    """

    assessment_id: int

    assessment_document_id: int

    extractions: list[AssessmentQuestionExtractionSummaryResponse] = Field(
        default_factory=list,
    )
