from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)

from app.models.assessment import AssessmentStatus
from app.models.assessment_candidate import (
    AssessmentCandidateStatus,
    AssessmentScriptStatus,
)
from app.models.assessment_question import (
    AssessmentQuestionAssetType,
    AssessmentQuestionType,
)
from app.models.assessment_response import AssessmentResponseStatus
from app.schemas.assessment_marking import _normalise_response_data

# ---------------------------------------------------------------------------
# Candidate-safe question content
# ---------------------------------------------------------------------------


class AssessmentTakingOptionOut(BaseModel):
    """
    Learner-safe structured answer option.

    Correctness and feedback are deliberately excluded.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    text: str
    order: int


class AssessmentTakingAssetOut(BaseModel):
    """
    Learner-safe question asset.

    Server-side storage paths, source-document identifiers, page coordinates,
    extraction provenance, and other internal metadata are deliberately
    excluded.

    ``content_url`` is an authorised API route generated by the endpoint/service
    layer. It is not persisted on AssessmentQuestionAsset.
    """

    id: int
    asset_type: AssessmentQuestionAssetType

    alt_text: str | None = None
    caption: str | None = None

    order: int

    content_url: str


class AssessmentTakingQuestionOut(BaseModel):
    """
    One learner-visible canonical assessment question.

    This schema deliberately excludes:
        - correct-option flags;
        - option feedback;
        - mark schemes;
        - marking decisions;
        - asset storage paths and extraction provenance.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    assessment_id: int

    section_id: int | None = None
    parent_question_id: int | None = None

    question_number: str

    title: str | None = None
    prompt: str | None = None

    question_type: AssessmentQuestionType

    maximum_mark: Decimal

    order: int
    is_markable: bool

    options: list[AssessmentTakingOptionOut] = Field(
        default_factory=list,
    )

    assets: list[AssessmentTakingAssetOut] = Field(
        default_factory=list,
    )


class AssessmentTakingSectionOut(BaseModel):
    """
    Learner-visible assessment section metadata.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    assessment_id: int

    title: str
    description: str | None = None

    order: int
    is_optional: bool


# ---------------------------------------------------------------------------
# Candidate-owned response payloads
# ---------------------------------------------------------------------------


class AssessmentTakingResponseSave(BaseModel):
    """
    Autosave payload for one learner response.

    ``question_id`` is carried in the route rather than the payload.

    ``response_data`` remains a string at the ORM/service boundary because the
    existing AssessmentResponse column is Text. New clients may nevertheless
    submit structured dictionaries; diagram-annotation payloads are validated
    and serialised by the shared response-data normaliser.

    ``source_reference`` is intentionally absent from learner input. It is
    internal provenance metadata and must not be forgeable by a browser client.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    response_text: str | None = None
    response_data: str | None = None

    @field_validator(
        "response_data",
        mode="before",
    )
    @classmethod
    def validate_response_data(
        cls,
        value: Any,
    ) -> str | None:
        return _normalise_response_data(value)


class AssessmentTakingResponseOut(BaseModel):
    """
    Learner-safe representation of one saved response.

    Marking decisions, marks, marker comments, moderation information and
    internal source references are deliberately excluded.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    question_id: int

    status: AssessmentResponseStatus

    response_text: str | None = None
    response_data: str | None = None

    created_at: datetime
    updated_at: datetime
    submitted_at: datetime | None = None


# ---------------------------------------------------------------------------
# Candidate-owned script state
# ---------------------------------------------------------------------------


class AssessmentTakingScriptOut(BaseModel):
    """
    Minimal learner-safe browser-script representation.

    Upload/storage metadata and marking timestamps are intentionally excluded.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    version: int
    status: AssessmentScriptStatus

    created_at: datetime
    submitted_at: datetime | None = None


# ---------------------------------------------------------------------------
# Student assessment listing
# ---------------------------------------------------------------------------


class StudentAssessmentSummaryOut(BaseModel):
    """
    One assessment allocation shown in the logged-in student's assessment list.

    The candidate record is resolved server-side from ``current_user.id``.
    Candidate IDs, candidate numbers, access-arrangement notes, storage metadata,
    marking data, and information about other candidates are not exposed.
    """

    assessment_id: int

    title: str
    description: str | None = None

    assessment_type: str | None = None
    academic_year: str | None = None
    term: str | None = None

    assessment_status: AssessmentStatus
    candidate_status: AssessmentCandidateStatus

    scheduled_at: datetime | None = None
    closes_at: datetime | None = None

    started_at: datetime | None = None
    submitted_at: datetime | None = None

    can_start: bool
    can_resume: bool
    is_submitted: bool


# ---------------------------------------------------------------------------
# Full learner attempt
# ---------------------------------------------------------------------------


class StudentAssessmentAttemptOut(BaseModel):
    """
    Full candidate-safe assessment-taking payload.

    The service supplies this only after:
        - active-user validation;
        - student-role validation;
        - candidate ownership validation;
        - school-scope validation;
        - assessment availability/lifecycle validation.

    The payload contains only the logged-in learner's own attempt state.
    """

    assessment_id: int

    title: str
    description: str | None = None

    assessment_type: str | None = None
    academic_year: str | None = None
    term: str | None = None

    assessment_status: AssessmentStatus
    candidate_status: AssessmentCandidateStatus

    scheduled_at: datetime | None = None
    closes_at: datetime | None = None

    started_at: datetime | None = None
    submitted_at: datetime | None = None

    script: AssessmentTakingScriptOut | None = None

    sections: list[AssessmentTakingSectionOut] = Field(
        default_factory=list,
    )

    questions: list[AssessmentTakingQuestionOut] = Field(
        default_factory=list,
    )

    responses: list[AssessmentTakingResponseOut] = Field(
        default_factory=list,
    )


class StudentAssessmentStartOut(StudentAssessmentAttemptOut):
    """
    Attempt payload returned after a learner starts or resumes an assessment.
    """

    message: str = "Assessment started."


class StudentAssessmentSubmitOut(BaseModel):
    """
    Confirmation returned after the learner submits the browser assessment.

    The submitted script and candidate are both transitioned atomically by the
    student-taking service. No marking information is exposed.
    """

    assessment_id: int

    candidate_status: AssessmentCandidateStatus
    script_status: AssessmentScriptStatus

    submitted_at: datetime

    message: str = "Assessment submitted."
