from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ImportValidationRuleRead(BaseModel):
    """
    Public representation of one validation rule derived from an import schema.

    Examples include minimum length, maximum length, accepted enum values,
    numeric bounds, regular-expression patterns and semantic formats such as
    email addresses or dates.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    name: str = Field(
        min_length=1,
        max_length=100,
    )

    value: Any

    description: str | None = Field(
        default=None,
        max_length=500,
    )


class ImportFieldMetadataRead(BaseModel):
    """
    Public metadata for one field accepted by an import type.

    Field order follows the authoritative Pydantic import schema so generated
    CSV files and frontend displays remain consistent with backend validation.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    name: str = Field(
        min_length=1,
        max_length=150,
    )

    column_name: str = Field(
        min_length=1,
        max_length=150,
    )

    label: str = Field(
        min_length=1,
        max_length=200,
    )

    required: bool

    nullable: bool

    data_type: str = Field(
        min_length=1,
        max_length=100,
    )

    python_type: str = Field(
        min_length=1,
        max_length=250,
    )

    description: str | None = Field(
        default=None,
        max_length=1000,
    )

    default: Any | None = None

    example: Any | None = None

    accepted_values: list[Any] = Field(
        default_factory=list,
    )

    validation_rules: list[ImportValidationRuleRead] = Field(
        default_factory=list,
    )


class ImportTemplateMetadataRead(BaseModel):
    """
    Complete metadata for one registered import template.

    The backend derives field information from the Pydantic schema registered
    with the import handler. Clients should use this response instead of
    maintaining hard-coded field definitions.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    import_type: str = Field(
        min_length=1,
        max_length=100,
    )

    display_name: str = Field(
        min_length=1,
        max_length=150,
    )

    description: str = Field(
        min_length=1,
        max_length=1000,
    )

    schema_name: str = Field(
        min_length=1,
        max_length=200,
    )

    fields: list[ImportFieldMetadataRead] = Field(
        default_factory=list,
    )

    required_fields: list[ImportFieldMetadataRead] = Field(
        default_factory=list,
    )

    optional_fields: list[ImportFieldMetadataRead] = Field(
        default_factory=list,
    )

    csv_headers: list[str] = Field(
        default_factory=list,
    )

    sample_row: dict[str, Any] = Field(
        default_factory=dict,
    )

    metadata_url: str | None = Field(
        default=None,
        max_length=500,
    )

    download_url: str | None = Field(
        default=None,
        max_length=500,
    )


class ImportTemplateSummaryRead(BaseModel):
    """
    Compact template representation used by discovery endpoints.

    This model allows clients to list available templates without loading all
    field-level metadata for every import type.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    import_type: str = Field(
        min_length=1,
        max_length=100,
    )

    display_name: str = Field(
        min_length=1,
        max_length=150,
    )

    description: str = Field(
        min_length=1,
        max_length=1000,
    )

    required_field_count: int = Field(
        ge=0,
    )

    optional_field_count: int = Field(
        ge=0,
    )

    total_field_count: int = Field(
        ge=0,
    )

    metadata_url: str | None = Field(
        default=None,
        max_length=500,
    )

    download_url: str | None = Field(
        default=None,
        max_length=500,
    )


class ImportTemplateListRead(BaseModel):
    """
    Discovery response containing all registered import templates.
    """

    items: list[ImportTemplateSummaryRead] = Field(
        default_factory=list,
    )

    total: int = Field(
        ge=0,
    )


class ImportTemplateCsvPreviewRead(BaseModel):
    """
    Text preview of a generated CSV import template.

    CSV whitespace and line endings are preserved exactly so the preview
    remains identical to the downloadable CSV generated by the template
    service.
    """

    model_config = ConfigDict(
        str_strip_whitespace=False,
    )

    import_type: str = Field(
        min_length=1,
        max_length=100,
    )

    filename: str = Field(
        min_length=1,
        max_length=255,
    )

    content_type: str = Field(
        default="text/csv",
        min_length=1,
        max_length=100,
    )

    csv_content: str
