"""create timetable system

Revision ID: 155cea059f2a
Revises: d954f056b73d
Create Date: 2026-05-16 14:54:00.377301+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155cea059f2a'
down_revision = 'd954f056b73d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_registration', sa.Boolean(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('is_lunch', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_periods_id'), 'timetable_periods', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_periods_school_id'), 'timetable_periods', ['school_id'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_academic_year'), 'timetables', ['academic_year'], unique=False)
    op.create_index(op.f('ix_timetables_effective_from'), 'timetables', ['effective_from'], unique=False)
    op.create_index(op.f('ix_timetables_effective_to'), 'timetables', ['effective_to'], unique=False)
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_index(op.f('ix_timetables_is_active'), 'timetables', ['is_active'], unique=False)
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_table('timetable_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.Enum('STUDENT', 'TEACHER', 'CLASS_GROUP', name='timetableassignmenttype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_id', 'assignment_type', 'user_id', 'class_group_id', name='uq_timetable_assignment_scope')
    )
    op.create_index(op.f('ix_timetable_assignments_assignment_type'), 'timetable_assignments', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_timetable_assignments_class_group_id'), 'timetable_assignments', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_timetable_assignments_id'), 'timetable_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_assignments_school_id'), 'timetable_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_assignments_timetable_id'), 'timetable_assignments', ['timetable_id'], unique=False)
    op.create_index(op.f('ix_timetable_assignments_user_id'), 'timetable_assignments', ['user_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('timetable_period_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='timetableday'), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_period_id'], ['timetable_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_class_group_id'), 'timetable_entries', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_course_id'), 'timetable_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_day_of_week'), 'timetable_entries', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_timetable_entries_id'), 'timetable_entries', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_school_id'), 'timetable_entries', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_teacher_id'), 'timetable_entries', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_timetable_id'), 'timetable_entries', ['timetable_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_timetable_period_id'), 'timetable_entries', ['timetable_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_timetable_period_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_timetable_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_teacher_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_school_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_day_of_week'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_course_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_class_group_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_timetable_assignments_user_id'), table_name='timetable_assignments')
    op.drop_index(op.f('ix_timetable_assignments_timetable_id'), table_name='timetable_assignments')
    op.drop_index(op.f('ix_timetable_assignments_school_id'), table_name='timetable_assignments')
    op.drop_index(op.f('ix_timetable_assignments_id'), table_name='timetable_assignments')
    op.drop_index(op.f('ix_timetable_assignments_class_group_id'), table_name='timetable_assignments')
    op.drop_index(op.f('ix_timetable_assignments_assignment_type'), table_name='timetable_assignments')
    op.drop_table('timetable_assignments')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_is_active'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_effective_to'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_effective_from'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_academic_year'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_timetable_periods_school_id'), table_name='timetable_periods')
    op.drop_index(op.f('ix_timetable_periods_id'), table_name='timetable_periods')
    op.drop_table('timetable_periods')
    # ### end Alembic commands ###