"""enforce current assessment document uniqueness

Revision ID: 211bb5431f31
Revises: a8605e8f478b
Create Date: 2026-08-17 19:10:05.410393+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211bb5431f31'
down_revision = 'a8605e8f478b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_assessment_documents_current_type', 'assessment_documents', ['assessment_id', 'document_type'], unique=True, postgresql_where=sa.text('is_current = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_assessment_documents_current_type', table_name='assessment_documents', postgresql_where=sa.text('is_current = true'))
    # ### end Alembic commands ###