"""add assessment marking annotations

Revision ID: 4d951a3fb71b
Revises: 6874378d94fe
Create Date: 2026-08-23 10:14:40.931533+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d951a3fb71b'
down_revision = '6874378d94fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_marking_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sa.Enum('symbol', 'code', 'text', 'line', 'arrow', 'highlight', name='marking_annotation_type', native_enum=False), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('label_snapshot', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('surface_type', sa.Enum('response', 'question_asset', 'script_page', name='marking_annotation_surface_type', native_enum=False), nullable=False),
    sa.Column('surface_reference', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('x', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('y', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_x', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_y', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('width', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('height', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('end_x IS NULL OR (end_x >= 0 AND end_x <= 1)', name='ck_assessment_marking_annotation_end_x_normalized'),
    sa.CheckConstraint('end_y IS NULL OR (end_y >= 0 AND end_y <= 1)', name='ck_assessment_marking_annotation_end_y_normalized'),
    sa.CheckConstraint('height IS NULL OR (height >= 0 AND height <= 1)', name='ck_assessment_marking_annotation_height_normalized'),
    sa.CheckConstraint('page_number IS NULL OR page_number >= 1', name='ck_assessment_marking_annotation_page_number_positive'),
    sa.CheckConstraint('revision >= 1', name='ck_assessment_marking_annotation_revision_positive'),
    sa.CheckConstraint('width IS NULL OR (width >= 0 AND width <= 1)', name='ck_assessment_marking_annotation_width_normalized'),
    sa.CheckConstraint('x >= 0 AND x <= 1', name='ck_assessment_marking_annotation_x_normalized'),
    sa.CheckConstraint('y >= 0 AND y <= 1', name='ck_assessment_marking_annotation_y_normalized'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['assessment_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_marking_annotations_annotation_type'), 'assessment_marking_annotations', ['annotation_type'], unique=False)
    op.create_index(op.f('ix_assessment_marking_annotations_deleted_at'), 'assessment_marking_annotations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_assessment_marking_annotations_deleted_by_id'), 'assessment_marking_annotations', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_assessment_marking_annotations_marker_id'), 'assessment_marking_annotations', ['marker_id'], unique=False)
    op.create_index(op.f('ix_assessment_marking_annotations_response_id'), 'assessment_marking_annotations', ['response_id'], unique=False)
    op.create_index(op.f('ix_assessment_marking_annotations_surface_type'), 'assessment_marking_annotations', ['surface_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_marking_annotations_surface_type'), table_name='assessment_marking_annotations')
    op.drop_index(op.f('ix_assessment_marking_annotations_response_id'), table_name='assessment_marking_annotations')
    op.drop_index(op.f('ix_assessment_marking_annotations_marker_id'), table_name='assessment_marking_annotations')
    op.drop_index(op.f('ix_assessment_marking_annotations_deleted_by_id'), table_name='assessment_marking_annotations')
    op.drop_index(op.f('ix_assessment_marking_annotations_deleted_at'), table_name='assessment_marking_annotations')
    op.drop_index(op.f('ix_assessment_marking_annotations_annotation_type'), table_name='assessment_marking_annotations')
    op.drop_table('assessment_marking_annotations')
    # ### end Alembic commands ###