"""update enrollments for class groups

Revision ID: 506d7407f307
Revises: 7bcee188e63f
Create Date: 2026-04-03 21:17:28.305231+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506d7407f307'
down_revision = '7bcee188e63f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('enrollments', sa.Column('class_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_course_student'), 'enrollments', type_='unique')
    op.create_index(op.f('ix_enrollments_class_id'), 'enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_unique_constraint('uq_enrollments_user_class', 'enrollments', ['user_id', 'class_id'])
    op.drop_constraint(op.f('enrollments_student_id_fkey'), 'enrollments', type_='foreignkey')
    op.drop_constraint(op.f('enrollments_course_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'class_groups', ['class_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'])
    op.drop_column('enrollments', 'course_id')
    op.drop_column('enrollments', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('enrollments', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_course_id_fkey'), 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('enrollments_student_id_fkey'), 'enrollments', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_enrollments_user_class', 'enrollments', type_='unique')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_class_id'), table_name='enrollments')
    op.create_unique_constraint(op.f('uq_course_student'), 'enrollments', ['course_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('enrollments', 'class_id')
    op.drop_column('enrollments', 'user_id')
    # ### end Alembic commands ###