"""prevent duplicate attendance records

Revision ID: 5c8413388149
Revises: 155cea059f2a
Create Date: 2026-05-16 18:48:44.538657+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8413388149'
down_revision = '155cea059f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attendance_session_student'), 'attendance_records', type_='unique')
    op.create_unique_constraint('uq_attendance_record_session_student', 'attendance_records', ['attendance_session_id', 'student_id'])
    op.add_column('attendance_sessions', sa.Column('timetable_entry_id', sa.Integer(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('timetable_period_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendance_sessions_timetable_entry_id'), 'attendance_sessions', ['timetable_entry_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_timetable_period_id'), 'attendance_sessions', ['timetable_period_id'], unique=False)
    op.create_foreign_key(None, 'attendance_sessions', 'timetable_periods', ['timetable_period_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attendance_sessions', 'timetable_entries', ['timetable_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_sessions_timetable_period_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_timetable_entry_id'), table_name='attendance_sessions')
    op.drop_column('attendance_sessions', 'timetable_period_id')
    op.drop_column('attendance_sessions', 'timetable_entry_id')
    op.drop_constraint('uq_attendance_record_session_student', 'attendance_records', type_='unique')
    op.create_unique_constraint(op.f('uq_attendance_session_student'), 'attendance_records', ['attendance_session_id', 'student_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###