"""link marking annotations to palette tools

Revision ID: 6a5b978acd5d
Revises: ca4ea053b930
Create Date: 2026-08-23 10:37:30.329913+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5b978acd5d'
down_revision = 'ca4ea053b930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_marking_annotations', sa.Column('palette_tool_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assessment_marking_annotations_palette_tool_id'), 'assessment_marking_annotations', ['palette_tool_id'], unique=False)
    op.create_foreign_key(None, 'assessment_marking_annotations', 'marking_palette_tools', ['palette_tool_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment_marking_annotations', type_='foreignkey')
    op.drop_index(op.f('ix_assessment_marking_annotations_palette_tool_id'), table_name='assessment_marking_annotations')
    op.drop_column('assessment_marking_annotations', 'palette_tool_id')
    # ### end Alembic commands ###