"""add assessment question extractions

Revision ID: 8aa9c6b5a49c
Revises: 211bb5431f31
Create Date: 2026-08-17 20:23:21.284677+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa9c6b5a49c'
down_revision = '211bb5431f31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_question_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('assessment_document_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('extractor_name', sa.String(length=100), server_default='pypdf', nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('parser_version', sa.String(length=50), server_default='1', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('text_page_count', sa.Integer(), nullable=True),
    sa.Column('detected_question_count', sa.Integer(), nullable=True),
    sa.Column('detected_markable_question_count', sa.Integer(), nullable=True),
    sa.Column('detected_total_marks', sa.Integer(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('page_data', sa.JSON(), nullable=True),
    sa.Column('proposal_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_document_id'], ['assessment_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_document_id', 'version', name='uq_assessment_question_extraction_document_version')
    )
    op.create_index(op.f('ix_assessment_question_extractions_assessment_document_id'), 'assessment_question_extractions', ['assessment_document_id'], unique=False)
    op.create_index('ix_assessment_question_extractions_assessment_document_status', 'assessment_question_extractions', ['assessment_document_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessment_question_extractions_assessment_id'), 'assessment_question_extractions', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_question_extractions_assessment_status', 'assessment_question_extractions', ['assessment_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessment_question_extractions_imported_by_id'), 'assessment_question_extractions', ['imported_by_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_extractions_requested_by_id'), 'assessment_question_extractions', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_extractions_status'), 'assessment_question_extractions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_question_extractions_status'), table_name='assessment_question_extractions')
    op.drop_index(op.f('ix_assessment_question_extractions_requested_by_id'), table_name='assessment_question_extractions')
    op.drop_index(op.f('ix_assessment_question_extractions_imported_by_id'), table_name='assessment_question_extractions')
    op.drop_index('ix_assessment_question_extractions_assessment_status', table_name='assessment_question_extractions')
    op.drop_index(op.f('ix_assessment_question_extractions_assessment_id'), table_name='assessment_question_extractions')
    op.drop_index('ix_assessment_question_extractions_assessment_document_status', table_name='assessment_question_extractions')
    op.drop_index(op.f('ix_assessment_question_extractions_assessment_document_id'), table_name='assessment_question_extractions')
    op.drop_table('assessment_question_extractions')
    # ### end Alembic commands ###