"""init

Revision ID: 9ddb5f2d3fde
Revises: 414a75244978
Create Date: 2026-03-09 20:48:12.683483+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddb5f2d3fde'
down_revision = '414a75244978'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###