"""add assessment documents

Revision ID: a8605e8f478b
Revises: 42fdd9b1822f
Create Date: 2026-08-16 21:21:19.890738+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8605e8f478b'
down_revision = '42fdd9b1822f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), server_default='question_paper', nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=2000), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('extraction_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extraction_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extraction_error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_documents_assessment_id'), 'assessment_documents', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_documents_assessment_type_current', 'assessment_documents', ['assessment_id', 'document_type', 'is_current'], unique=False)
    op.create_index(op.f('ix_assessment_documents_document_type'), 'assessment_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_assessment_documents_is_current'), 'assessment_documents', ['is_current'], unique=False)
    op.create_index(op.f('ix_assessment_documents_uploaded_by_id'), 'assessment_documents', ['uploaded_by_id'], unique=False)
    op.drop_index(op.f('ix_parent_students_id'), table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_parent_id'), table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_student_id'), table_name='parent_students')
    op.drop_table('parent_students')
    op.alter_column('report_sessions', 'display_order',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('report_sessions', 'reporting_mode',
               existing_type=sa.VARCHAR(length=30),
               server_default='full_report',
               existing_nullable=False)
    op.alter_column('report_sessions', 'active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_work_covered',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_student_comment',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_exam_mark',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_effort_grade',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_attainment_grade',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_target_grade',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_next_steps',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_tutor_comment',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('student_reports', 'report_text',
               existing_type=sa.TEXT(),
               server_default='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_reports', 'report_text',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_tutor_comment',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_next_steps',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_target_grade',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_attainment_grade',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_effort_grade',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_exam_mark',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_student_comment',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'include_work_covered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'reporting_mode',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_sessions', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_table('parent_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_students_parent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_students_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_students')),
    sa.UniqueConstraint('parent_id', 'student_id', name=op.f('uq_parent_student'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_parent_students_student_id'), 'parent_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_parent_students_parent_id'), 'parent_students', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_students_id'), 'parent_students', ['id'], unique=False)
    op.drop_index(op.f('ix_assessment_documents_uploaded_by_id'), table_name='assessment_documents')
    op.drop_index(op.f('ix_assessment_documents_is_current'), table_name='assessment_documents')
    op.drop_index(op.f('ix_assessment_documents_document_type'), table_name='assessment_documents')
    op.drop_index('ix_assessment_documents_assessment_type_current', table_name='assessment_documents')
    op.drop_index(op.f('ix_assessment_documents_assessment_id'), table_name='assessment_documents')
    op.drop_table('assessment_documents')
    # ### end Alembic commands ###