"""link student reports to report sessions

Revision ID: c4a8f4af691f
Revises: e8676cb4fa4e
Create Date: 2026-06-16 20:35:55.831630+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a8f4af691f'
down_revision = 'e8676cb4fa4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignment_submissions_graded_by_fkey'), 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_submissions', 'users', ['graded_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_message_attachments_mime_type'), 'message_attachments', ['mime_type'], unique=False)
    op.create_index(op.f('ix_message_deliveries_id'), 'message_deliveries', ['id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    op.add_column('student_reports', sa.Column('report_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_reports_report_session_id'), 'student_reports', ['report_session_id'], unique=False)
    op.create_foreign_key(None, 'student_reports', 'report_sessions', ['report_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_reports', type_='foreignkey')
    op.drop_index(op.f('ix_student_reports_report_session_id'), table_name='student_reports')
    op.drop_column('student_reports', 'report_session_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_message_deliveries_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_attachments_mime_type'), table_name='message_attachments')
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_submissions_graded_by_fkey'), 'assignment_submissions', 'users', ['graded_by'], ['id'])
    # ### end Alembic commands ###