"""add marking palettes

Revision ID: ca4ea053b930
Revises: 4d951a3fb71b
Create Date: 2026-08-23 10:32:53.179973+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4ea053b930'
down_revision = '4d951a3fb71b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marking_palettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_marking_palette_school_name')
    )
    op.create_index(op.f('ix_marking_palettes_is_active'), 'marking_palettes', ['is_active'], unique=False)
    op.create_index(op.f('ix_marking_palettes_is_default'), 'marking_palettes', ['is_default'], unique=False)
    op.create_index(op.f('ix_marking_palettes_school_id'), 'marking_palettes', ['school_id'], unique=False)
    op.create_index(op.f('ix_marking_palettes_subject_id'), 'marking_palettes', ['subject_id'], unique=False)
    op.create_table('marking_palette_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palette_id', sa.Integer(), nullable=False),
    sa.Column('tool_type', sa.Enum('symbol', 'code', 'text', 'line', 'arrow', 'highlight', name='marking_palette_tool_type', native_enum=False), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keyboard_shortcut', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['palette_id'], ['marking_palettes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('palette_id', 'tool_type', 'value', name='uq_marking_palette_tool_palette_type_value')
    )
    op.create_index(op.f('ix_marking_palette_tools_is_active'), 'marking_palette_tools', ['is_active'], unique=False)
    op.create_index(op.f('ix_marking_palette_tools_palette_id'), 'marking_palette_tools', ['palette_id'], unique=False)
    op.create_index(op.f('ix_marking_palette_tools_sort_order'), 'marking_palette_tools', ['sort_order'], unique=False)
    op.create_index(op.f('ix_marking_palette_tools_tool_type'), 'marking_palette_tools', ['tool_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marking_palette_tools_tool_type'), table_name='marking_palette_tools')
    op.drop_index(op.f('ix_marking_palette_tools_sort_order'), table_name='marking_palette_tools')
    op.drop_index(op.f('ix_marking_palette_tools_palette_id'), table_name='marking_palette_tools')
    op.drop_index(op.f('ix_marking_palette_tools_is_active'), table_name='marking_palette_tools')
    op.drop_table('marking_palette_tools')
    op.drop_index(op.f('ix_marking_palettes_subject_id'), table_name='marking_palettes')
    op.drop_index(op.f('ix_marking_palettes_school_id'), table_name='marking_palettes')
    op.drop_index(op.f('ix_marking_palettes_is_default'), table_name='marking_palettes')
    op.drop_index(op.f('ix_marking_palettes_is_active'), table_name='marking_palettes')
    op.drop_table('marking_palettes')
    # ### end Alembic commands ###