"""add attendance register locking

Revision ID: d74321c2ffcd
Revises: 5cad7798514b
Create Date: 2026-05-16 20:53:05.332265+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74321c2ffcd'
down_revision = '5cad7798514b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###