"""create attendance system

Revision ID: d954f056b73d
Revises: d6a4f690a68e
Create Date: 2026-05-16 13:11:10.124574+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd954f056b73d'
down_revision = 'd6a4f690a68e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('absence_type', sa.Enum('PLANNED', 'UNPLANNED', name='absence_request_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='absence_request_status', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absence_requests_absence_type'), 'absence_requests', ['absence_type'], unique=False)
    op.create_index(op.f('ix_absence_requests_end_date'), 'absence_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_absence_requests_id'), 'absence_requests', ['id'], unique=False)
    op.create_index(op.f('ix_absence_requests_reviewed_by_id'), 'absence_requests', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_absence_requests_school_id'), 'absence_requests', ['school_id'], unique=False)
    op.create_index(op.f('ix_absence_requests_start_date'), 'absence_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_absence_requests_status'), 'absence_requests', ['status'], unique=False)
    op.create_index(op.f('ix_absence_requests_student_id'), 'absence_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_absence_requests_submitted_by_id'), 'absence_requests', ['submitted_by_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('AM', 'PM', name='attendance_session_type', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_group_id', 'session_date', 'session_type', name='uq_attendance_session_school_class_date_type')
    )
    op.create_index(op.f('ix_attendance_sessions_class_group_id'), 'attendance_sessions', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_created_by_id'), 'attendance_sessions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_id'), 'attendance_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_school_id'), 'attendance_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_date'), 'attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_type'), 'attendance_sessions', ['session_type'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'AUTHORISED_ABSENCE', 'UNAUTHORISED_ABSENCE', name='attendance_status', native_enum=False), nullable=False),
    sa.Column('marked_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_attendance_session_student')
    )
    op.create_index(op.f('ix_attendance_records_attendance_session_id'), 'attendance_records', ['attendance_session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_marked_by_id'), 'attendance_records', ['marked_by_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_marked_by_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_sessions_session_type'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_school_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_created_by_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_class_group_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_absence_requests_submitted_by_id'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_student_id'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_status'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_start_date'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_school_id'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_reviewed_by_id'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_id'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_end_date'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_absence_type'), table_name='absence_requests')
    op.drop_table('absence_requests')
    # ### end Alembic commands ###