"""add marking decision revision history

Revision ID: e17c2d42c51b
Revises: 6a5b978acd5d
Create Date: 2026-08-23 21:19:21.367007+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17c2d42c51b'
down_revision = '6a5b978acd5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marking_decision_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marking_decision_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.Enum('updated', 'instant_marked', 'started', 'marked', 'reviewed', 'finalised', name='marking_decision_revision_change_type', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('manual', 'quick_mark', 'automated', 'ai', name='marking_decision_revision_source', native_enum=False), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unmarked', 'in_progress', 'marked', 'reviewed', 'finalised', name='marking_decision_revision_status', native_enum=False), nullable=False),
    sa.Column('mark_awarded', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('marker_comment', sa.Text(), nullable=True),
    sa.Column('moderation_comment', sa.Text(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_marking_decision_revision_positive'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marking_decision_id'], ['marking_decisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['response_id'], ['assessment_responses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marking_decision_id', 'revision', name='uq_marking_decision_revision_number')
    )
    op.create_index(op.f('ix_marking_decision_revisions_change_type'), 'marking_decision_revisions', ['change_type'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_changed_by_id'), 'marking_decision_revisions', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_created_at'), 'marking_decision_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_marker_id'), 'marking_decision_revisions', ['marker_id'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_marking_decision_id'), 'marking_decision_revisions', ['marking_decision_id'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_response_id'), 'marking_decision_revisions', ['response_id'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_source'), 'marking_decision_revisions', ['source'], unique=False)
    op.create_index(op.f('ix_marking_decision_revisions_status'), 'marking_decision_revisions', ['status'], unique=False)
    op.add_column(
        'marking_decisions',
        sa.Column(
            'revision',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        'ck_marking_decision_revision_non_negative',
        'marking_decisions',
        'revision >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_marking_decision_revision_non_negative',
        'marking_decisions',
        type_='check',
    )
    op.drop_column('marking_decisions', 'revision')
    op.drop_index(op.f('ix_marking_decision_revisions_status'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_source'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_response_id'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_marking_decision_id'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_marker_id'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_created_at'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_changed_by_id'), table_name='marking_decision_revisions')
    op.drop_index(op.f('ix_marking_decision_revisions_change_type'), table_name='marking_decision_revisions')
    op.drop_table('marking_decision_revisions')
    # ### end Alembic commands ###