"""add assessment question interaction config

Revision ID: e4258b9b91db
Revises: 16e3e4616f64
Create Date: 2026-08-21 10:44:54.320025+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4258b9b91db'
down_revision = '16e3e4616f64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_questions', sa.Column('interaction_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_questions', 'interaction_config')
    # ### end Alembic commands ###