"""make course school_id required

Revision ID: ec57c3bd4cb2
Revises: 6adb69d154cf
Create Date: 2026-04-02 20:49:26.621324+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec57c3bd4cb2'
down_revision = '6adb69d154cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_courses_school_id'), 'courses', ['school_id'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.drop_constraint(op.f('courses_school_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_school_id_fkey'), 'courses', 'schools', ['school_id'], ['id'])
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_school_id'), table_name='courses')
    op.alter_column('courses', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###