"""add assessment question snapshots

Revision ID: fbef62a0cb7e
Revises: e4258b9b91db
Create Date: 2026-08-22 18:29:33.670960+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbef62a0cb7e'
down_revision = 'e4258b9b91db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_question_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('parent_question_id_snapshot', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('interaction_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('maximum_mark', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_markable', sa.Boolean(), nullable=False),
    sa.Column('section_snapshot', sa.JSON(), nullable=True),
    sa.Column('options_snapshot', sa.JSON(), nullable=False),
    sa.Column('assets_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['script_id'], ['assessment_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'question_id', name='uq_assessment_question_snapshot_script_question')
    )
    op.create_index(op.f('ix_assessment_question_snapshots_question_id'), 'assessment_question_snapshots', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_snapshots_question_type'), 'assessment_question_snapshots', ['question_type'], unique=False)
    op.create_index(op.f('ix_assessment_question_snapshots_script_id'), 'assessment_question_snapshots', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_question_snapshots_script_id'), table_name='assessment_question_snapshots')
    op.drop_index(op.f('ix_assessment_question_snapshots_question_type'), table_name='assessment_question_snapshots')
    op.drop_index(op.f('ix_assessment_question_snapshots_question_id'), table_name='assessment_question_snapshots')
    op.drop_table('assessment_question_snapshots')
    # ### end Alembic commands ###