"""add assignments and submissions

Revision ID: fdaaec6b809c
Revises: 506d7407f307
Create Date: 2026-04-05 11:38:47.835172+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaaec6b809c'
down_revision = '506d7407f307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###