"""modules_lessons_progress

Revision ID: 2b981609f287
Revises: 999694bb2b57
Create Date: 2026-03-11 21:02:29.031840+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b981609f287'
down_revision = '999694bb2b57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###