"""modules_lessons_progress

Revision ID: 9173b7e08e72
Revises: e0446afdf3bd
Create Date: 2026-03-06 21:37:52.287205+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9173b7e08e72'
down_revision = 'e0446afdf3bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###