"""modules_lessons_progress

Revision ID: 98083b184bb7
Revises: 9ddb5f2d3fde
Create Date: 2026-03-09 21:33:48.089251+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98083b184bb7'
down_revision = '9ddb5f2d3fde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###